version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/scripts:/app/scripts  # Shared scripts folder
    depends_on:
      - execution
      - db  # Ensures DB is up before backend starts (if needed)

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  execution:
    build: ./execution
    container_name: script-executor
    volumes:
      - ./backend/scripts:/app/scripts  # Same shared volume for accessing scripts

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
